# Generated by Django 5.2.4 on 2026-01-26 07:28

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "short_id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        max_length=22,
                        unique=True,
                    ),
                ),
                ("blood_group", models.CharField(max_length=3)),
                ("patient_name", models.CharField(max_length=100)),
                ("urgency", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=100)),
                ("status", models.CharField(default="Pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcceptedDonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        max_length=22,
                        unique=True,
                    ),
                ),
                ("status", models.CharField(default="Pending", max_length=20)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accepted_donors",
                        to="donations.request",
                    ),
                ),
            ],
        ),
    ]
