# Generated by Django 5.2.4 on 2026-01-26 08:09

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accepteddonor",
            name="unique_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="short_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True
            ),
        ),
    ]
