# Generated by Django 5.2.4 on 2026-01-26 09:34

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0002_alter_accepteddonor_unique_id_alter_request_short_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="patient_age",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="pincode",
            field=models.CharField(default=-1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="request",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accepteddonor",
            name="unique_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid, max_length=22, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="location",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="request",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="short_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="urgency",
            field=models.CharField(
                choices=[("Emergency", "Emergency"), ("Not Urgent", "Not Urgent")],
                max_length=15,
            ),
        ),
    ]
