# Generated by Django 5.2.4 on 2026-01-26 12:40

import django.db.models.deletion
import django.utils.timezone
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donations",
            "0003_request_patient_age_request_pincode_request_reason_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accepteddonor",
            name="accepted_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="accepteddonor",
            name="donor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="accepteddonor",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Finalized", "Finalized"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="accepteddonor",
            name="unique_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="short_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
    ]
