# Generated by Django 5.2.4 on 2026-01-31 15:15

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0005_alter_accepteddonor_unique_id_alter_request_short_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accepteddonor",
            name="unique_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="short_id",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Success", "Success"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
